### ISSUE TITLE
Tip: remind developers that the `data` permission should be spelled `'data:'`

### ISSUE THREAD

**Issue by jacob414** [twaldear/flask-csp#1]
I know it's redundant and already mentioned in the guide you link to, but it could be helpful to remind users that the `data` permission is spelled with a colon, e.g.:

```
@csp_header({'default-src':"'none'",'script-src':"'self'", 'font-src': "data: 'self'"})
```

..if you are a little sloppy and in a hurry like me it was quite possible to lose a bit of time there.

Thanks for a nice extension!

**Comment by twaldear** [comment]
Thanks for the feedback! I updated the readme with this information.
