### ISSUE TITLE
Error with comma in csp.py: "except Exception, e:"

### ISSUE THREAD

**Issue by ghost** [twaldear/flask-csp#8]
F:\Coding\app> python dash.py
Traceback (most recent call last):
  File "dash.py", line 3, in <module>
    from flask_csp.csp import csp_header
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask_csp\csp.py", line 14
    except Exception, e:

**Comment by ghost** [comment]
edited csp.py line 14 to read as it does in git:
"except Exception as e:"

Works fine. The version currently available in pip is incorrect.

**Comment by metachris** [comment]
@twaldear can you update this to make it work with Python 3?

**Comment by ashleysommer** [comment]
This was reported and fixed in Feb 2017 as reported here: https://github.com/twaldear/flask-csp/issues/5
But there hasn't been a new version pushed to PyPI since then.

**Comment by twaldear** [comment]
sorry i must not have pushed the package up to pypi. version 0.10 is there now so this bug should be fixed via pip installs
